#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 1920x1080 --rotate normal --same-as eDP-1
fi

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1-0 -d 6 7 8 9 10

$HOME/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a Spotify desktop='^5'
bspc rule -a Zathura state=tiled

wmname LG3D
