#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# laptop
if [[ $(xrandr -q | grep 'eDP-1 connected') ]]; then
    # application rules
    bspc rule -a Spotify desktop='^7' focus=off
    bspc rule -a discord desktop='^8' focus=off

    # workspaces
    bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8

    # configure trackpad
    xinput set-prop "Synaptics TM3625-010" "libinput Tapping Enabled" 1
    xinput set-prop "Synaptics TM3625-010" "libinput Natural Scrolling Enabled" 1
    xinput set-button-map "Synaptics TM3625-010" 1 1 1 4 5 6 7

    # configure mouse
    xinput set-prop "pointer:Logitech G305" "libinput Accel Profile Enabled" 0, 1
fi

# laptop external screen
if [[ $(xrandr -q | grep 'HDMI-1-0 connected') ]]; then
    xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 2560x1440 --rotate normal --right-of eDP-1
    bspc monitor HDMI-1-0 -d 6 7 8 9 10
fi

$HOME/.config/polybar/launch.sh

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Firefox desktop='^2'
bspc rule -a Zathura state=tiled

wmname LG3D
